name: scratchify
description: "A Flutter package for creating interactive scratch card widgets."
repository: https://github.com/Ramsthr/Scartchify
homepage: https://github.com/Ramsthr/Scartchify
issue_tracker: https://github.com/Ramsthr/Scartchify/issues

version: 1.0.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

